source "https://rubygems.org"

gem "jekyll", "~> 4.4"
gem "jekyll-remote-theme", github: "benbalter/jekyll-remote-theme", ref: "v0.4.3"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jekyll-feed"
gem "jekyll-paginate"
gem "jekyll-gist"
gem "webrick"
